'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ServicesPlus.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Property() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Property", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Resume() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Resume", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Services+.
        '''</summary>
        Friend ReadOnly Property AppTitle() As String
            Get
                Return ResourceManager.GetString("AppTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CopyFileLocation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CopyFileLocation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property csv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("csv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dropdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dropdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exportBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exportBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exportWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exportWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filter_clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter-clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filtering() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filtering", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grouping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grouping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property html() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("html", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InstallService() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InstallService", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description:.
        '''</summary>
        Friend ReadOnly Property LBLDescription() As String
            Get
                Return ResourceManager.GetString("LBLDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display name:.
        '''</summary>
        Friend ReadOnly Property LBLDisplayName() As String
            Get
                Return ResourceManager.GetString("LBLDisplayName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log on:.
        '''</summary>
        Friend ReadOnly Property LBLLogonAs() As String
            Get
                Return ResourceManager.GetString("LBLLogonAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Memory:.
        '''</summary>
        Friend ReadOnly Property LBLMemory() As String
            Get
                Return ResourceManager.GetString("LBLMemory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Path to executable:.
        '''</summary>
        Friend ReadOnly Property LBLPath() As String
            Get
                Return ResourceManager.GetString("LBLPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pause:.
        '''</summary>
        Friend ReadOnly Property LBLPause() As String
            Get
                Return ResourceManager.GetString("LBLPause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Peak Memory:.
        '''</summary>
        Friend ReadOnly Property LBLPeakMemory() As String
            Get
                Return ResourceManager.GetString("LBLPeakMemory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service name:.
        '''</summary>
        Friend ReadOnly Property LBLServiceName() As String
            Get
                Return ResourceManager.GetString("LBLServiceName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service status:.
        '''</summary>
        Friend ReadOnly Property LBLServiceStatus() As String
            Get
                Return ResourceManager.GetString("LBLServiceStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup type:.
        '''</summary>
        Friend ReadOnly Property LBLStartType() As String
            Get
                Return ResourceManager.GetString("LBLStartType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OpenFileLocation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFileLocation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Restart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Restart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Server() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Server", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ShowSystem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShowSystem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sorting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sorting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Local Computer ({0}).
        '''</summary>
        Friend ReadOnly Property TempLocalComputer() As String
            Get
                Return ResourceManager.GetString("TempLocalComputer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This feature requires &quot;Remote Registry&quot; service
        '''Please run the service on {0}.
        '''</summary>
        Friend ReadOnly Property TempPerformanceWarning() As String
            Get
                Return ResourceManager.GetString("TempPerformanceWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} ({1}).
        '''</summary>
        Friend ReadOnly Property TempPropertiesCaption() As String
            Get
                Return ResourceManager.GetString("TempPropertiesCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 100 Services.
        '''</summary>
        Friend ReadOnly Property TempServices() As String
            Get
                Return ResourceManager.GetString("TempServices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Server.
        '''</summary>
        Friend ReadOnly Property TextAddServerCaption() As String
            Get
                Return ResourceManager.GetString("TextAddServerCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select the computer you want Services+ to manage..
        '''</summary>
        Friend ReadOnly Property TextAddServerIntro() As String
            Get
                Return ResourceManager.GetString("TextAddServerIntro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Another Computer:.
        '''</summary>
        Friend ReadOnly Property TextAnotherComputer() As String
            Get
                Return ResourceManager.GetString("TextAnotherComputer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply.
        '''</summary>
        Friend ReadOnly Property TextApply() As String
            Get
                Return ResourceManager.GetString("TextApply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automatic.
        '''</summary>
        Friend ReadOnly Property TextAutomatic() As String
            Get
                Return ResourceManager.GetString("TextAutomatic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property TextCancel() As String
            Get
                Return ResourceManager.GetString("TextCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend ReadOnly Property TextClose() As String
            Get
                Return ResourceManager.GetString("TextClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy file location.
        '''</summary>
        Friend ReadOnly Property TextCopyFileLocation() As String
            Get
                Return ResourceManager.GetString("TextCopyFileLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSV Format.
        '''</summary>
        Friend ReadOnly Property TextCSVFormat() As String
            Get
                Return ResourceManager.GetString("TextCSVFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dependencies.
        '''</summary>
        Friend ReadOnly Property TextDependencies() As String
            Get
                Return ResourceManager.GetString("TextDependencies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend ReadOnly Property TextDescription() As String
            Get
                Return ResourceManager.GetString("TextDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Details.
        '''</summary>
        Friend ReadOnly Property TextDetails() As String
            Get
                Return ResourceManager.GetString("TextDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disabled.
        '''</summary>
        Friend ReadOnly Property TextDisabled() As String
            Get
                Return ResourceManager.GetString("TextDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend ReadOnly Property TextDisplayName() As String
            Get
                Return ResourceManager.GetString("TextDisplayName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend ReadOnly Property TextEdit() As String
            Get
                Return ResourceManager.GetString("TextEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error Details.
        '''</summary>
        Friend ReadOnly Property TextErrorCaption() As String
            Get
                Return ResourceManager.GetString("TextErrorCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export.
        '''</summary>
        Friend ReadOnly Property TextExport() As String
            Get
                Return ResourceManager.GetString("TextExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter.
        '''</summary>
        Friend ReadOnly Property TextFilter() As String
            Get
                Return ResourceManager.GetString("TextFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter ....
        '''</summary>
        Friend ReadOnly Property TextFilterSearch() As String
            Get
                Return ResourceManager.GetString("TextFilterSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to General.
        '''</summary>
        Friend ReadOnly Property TextGeneral() As String
            Get
                Return ResourceManager.GetString("TextGeneral", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Group by.
        '''</summary>
        Friend ReadOnly Property TextGroupBy() As String
            Get
                Return ResourceManager.GetString("TextGroupBy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group by log on.
        '''</summary>
        Friend ReadOnly Property TextGroupByLogOn() As String
            Get
                Return ResourceManager.GetString("TextGroupByLogOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group by startup.
        '''</summary>
        Friend ReadOnly Property TextGroupByStartupType() As String
            Get
                Return ResourceManager.GetString("TextGroupByStartupType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group by status.
        '''</summary>
        Friend ReadOnly Property TextGroupByStatus() As String
            Get
                Return ResourceManager.GetString("TextGroupByStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group by type.
        '''</summary>
        Friend ReadOnly Property TextGroupByType() As String
            Get
                Return ResourceManager.GetString("TextGroupByType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Html Format.
        '''</summary>
        Friend ReadOnly Property TextHtmlFormat() As String
            Get
                Return ResourceManager.GetString("TextHtmlFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to KEY.
        '''</summary>
        Friend ReadOnly Property TextKey() As String
            Get
                Return ResourceManager.GetString("TextKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Large Icon.
        '''</summary>
        Friend ReadOnly Property TextLargeIcon() As String
            Get
                Return ResourceManager.GetString("TextLargeIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List.
        '''</summary>
        Friend ReadOnly Property TextList() As String
            Get
                Return ResourceManager.GetString("TextList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log On As.
        '''</summary>
        Friend ReadOnly Property TextLogon() As String
            Get
                Return ResourceManager.GetString("TextLogon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manual.
        '''</summary>
        Friend ReadOnly Property TextManual() As String
            Get
                Return ResourceManager.GetString("TextManual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property TextNone() As String
            Get
                Return ResourceManager.GetString("TextNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ok.
        '''</summary>
        Friend ReadOnly Property TextOk() As String
            Get
                Return ResourceManager.GetString("TextOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open file location.
        '''</summary>
        Friend ReadOnly Property TextOpenFileLocation() As String
            Get
                Return ResourceManager.GetString("TextOpenFileLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pause.
        '''</summary>
        Friend ReadOnly Property TextPause() As String
            Get
                Return ResourceManager.GetString("TextPause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paused.
        '''</summary>
        Friend ReadOnly Property TextPaused() As String
            Get
                Return ResourceManager.GetString("TextPaused", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pause the service.
        '''</summary>
        Friend ReadOnly Property TextPauseTheService() As String
            Get
                Return ResourceManager.GetString("TextPauseTheService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Performance.
        '''</summary>
        Friend ReadOnly Property TextPerformance() As String
            Get
                Return ResourceManager.GetString("TextPerformance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Properties.
        '''</summary>
        Friend ReadOnly Property TextProperties() As String
            Get
                Return ResourceManager.GetString("TextProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh.
        '''</summary>
        Friend ReadOnly Property TextRefresh() As String
            Get
                Return ResourceManager.GetString("TextRefresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restart.
        '''</summary>
        Friend ReadOnly Property TextRestart() As String
            Get
                Return ResourceManager.GetString("TextRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restart the service.
        '''</summary>
        Friend ReadOnly Property TextRestartTheService() As String
            Get
                Return ResourceManager.GetString("TextRestartTheService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resume.
        '''</summary>
        Friend ReadOnly Property TextResume() As String
            Get
                Return ResourceManager.GetString("TextResume", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resume the service.
        '''</summary>
        Friend ReadOnly Property TextResumeTheService() As String
            Get
                Return ResourceManager.GetString("TextResumeTheService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Running.
        '''</summary>
        Friend ReadOnly Property TextRunning() As String
            Get
                Return ResourceManager.GetString("TextRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ServiceName.
        '''</summary>
        Friend ReadOnly Property TextServiceName() As String
            Get
                Return ResourceManager.GetString("TextServiceName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend ReadOnly Property TextServiceType() As String
            Get
                Return ResourceManager.GetString("TextServiceType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show all.
        '''</summary>
        Friend ReadOnly Property TextShowAll() As String
            Get
                Return ResourceManager.GetString("TextShowAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort Ascending.
        '''</summary>
        Friend ReadOnly Property TextSortAscending() As String
            Get
                Return ResourceManager.GetString("TextSortAscending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort Descending.
        '''</summary>
        Friend ReadOnly Property TextSortDescending() As String
            Get
                Return ResourceManager.GetString("TextSortDescending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start.
        '''</summary>
        Friend ReadOnly Property TextStart() As String
            Get
                Return ResourceManager.GetString("TextStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start the service.
        '''</summary>
        Friend ReadOnly Property TextStartTheService() As String
            Get
                Return ResourceManager.GetString("TextStartTheService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup Type.
        '''</summary>
        Friend ReadOnly Property TextStartType() As String
            Get
                Return ResourceManager.GetString("TextStartType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend ReadOnly Property TextStatus() As String
            Get
                Return ResourceManager.GetString("TextStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop.
        '''</summary>
        Friend ReadOnly Property TextStop() As String
            Get
                Return ResourceManager.GetString("TextStop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stopped.
        '''</summary>
        Friend ReadOnly Property TextStopped() As String
            Get
                Return ResourceManager.GetString("TextStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop the service.
        '''</summary>
        Friend ReadOnly Property TextStopTheService() As String
            Get
                Return ResourceManager.GetString("TextStopTheService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System.
        '''</summary>
        Friend ReadOnly Property TextSystem() As String
            Get
                Return ResourceManager.GetString("TextSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test &amp;&amp; Connect.
        '''</summary>
        Friend ReadOnly Property TextTestAndConnect() As String
            Get
                Return ResourceManager.GetString("TextTestAndConnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tile.
        '''</summary>
        Friend ReadOnly Property TextTile() As String
            Get
                Return ResourceManager.GetString("TextTile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tiles.
        '''</summary>
        Friend ReadOnly Property TextTiles() As String
            Get
                Return ResourceManager.GetString("TextTiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;View.
        '''</summary>
        Friend ReadOnly Property TextView() As String
            Get
                Return ResourceManager.GetString("TextView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property View() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("View", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ViewDetails() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ViewDetails", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ViewIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ViewIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ViewList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ViewList", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ViewTile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ViewTile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ViewWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ViewWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
